version: '3'

services:
    redis:
        image: redis:latest
    
    node:
        build:
            context: ./node
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis://redis
            PORT: 5000
        ports:
            - "5000:5000"